// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wivbfxjqydkozyvlabil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpdmJmeGpxeWRrb3p5dmxhYmlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNTgyNTEsImV4cCI6MjA1MDYzNDI1MX0.x4Urg5GXrHid96CK8z1qy6GsMENQCpfJynP0_x4WQ3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);